# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:9.6
    container_name: 'babacloud-database'
    restart: always
    environment:
      - "constraint:node.labels.purpose==general"
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Cr0ust1bat

volumes:
  pgdata: